name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update files
      run: |
        git pull origin main

    - name: Build Docker image
      run: |
        docker build -t your-image-name:$GITHUB_SHA .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push your-image-name:$GITHUB_SHA

    - name: Update Kubernetes Deployment
      run: kubectl apply -f path-to-your-kubernetes-file.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
